USE WAREHOUSE DEMO_WAREHOUSE;
USE DATABASE DEMO_DATABASE;
--GET CURRENT DATE
SELECT CURRENT_DATE;
--GET CURRENT TIME
SELECT CURRENT_TIMESTAMP; --2023-01-02 02:05:15.870 -0800,IN TIMESTAMP DATE,MONTH etc.ARE INVOLVED
SELECT CURRENT_TIME;--02:06:06,WHEREAS DATE IS NOT INVOLVED

--CONVERT TIMEZONE
SELECT CONVERT_TIMEZONE('UTC',CURRENT_TIMESTAMP) AS UTC_TIMEZONE;
select convert_timezone('America/Los_Angeles',CURRENT_TIMESTAMP) AS AMERICA_TIMEZONE  ;

--GET YR FROM DATE
SELECT DATE_TRUNC('YEAR',CURRENT_DATE) AS YEAR_FROM_DATE; --IF CLIENT WANTS IN YYYY-MM-DD FORMAT THEN USE THIS FUNCTION

--GET MONTH FROM DATE
SELECT DATE_TRUNC('MONTH',CURRENT_DATE) AS MONTH_FROM_DATE;

--GET DAY FROM DATE
SELECT DATE_TRUNC('DAY',CURRENT_DATE) AS DATE_FROM_DATE;
SELECT DATE_TRUNC('DAY',CURRENT_TIMESTAMP) AS DATE_FROM_DATE;
--GET WEEK FROM DATE
SELECT DATE_TRUNC('WEEK',CURRENT_DATE) AS START_OF_WEEK_DATE_FROM_DATE;--IT CONSIDER THE START OF THE WEEK AS MONDAY SO IT WILL GIVE RESULT WHEN MONDAY OCCUR OF THAT WEEK
SELECT DATE_TRUNC('WEEK',DATE('2023-01-25')) AS START_OF_WEEK_DATE_FROM_DATE;--IT WILL GIVE THE DATE UNTIL THE START OF THE WEEK WE ARE IN

--GET YR FROM DATE
SELECT DATE_TRUNC('YEAR',DATE('2021-08-08')) AS YEAR_FROM_DATE;
SELECT DATE_TRUNC('YEAR',TO_DATE('2021-08-08') AS YEAR_FROM_DATE;
                  
SELECT DATE('2004-07-24') AS INITIAL,DATE('2003-09-24') AS FINAL;
                  

SELECT current_timestamp();   
select day(current_timestamp()),
       hour(current_timestamp()),
       minute(current_timestamp()),
       month(current_timestamp());

select week(current_date) as week_from_start_of_the_year;            --NO OF WEEKS FROM START OF THE YEAR
select week(DATE('2021-08-08')) as week_from_start_of_the_year; 
SELECT DATE_TRUNC('WEEK',DATE('2021-08-08')) AS DATE_FROM_DATE;
                  
select month(current_date) as month_from_start_of_the_year;             --NO OF MONTH FROM START OF THE YEAR 
select Month(DATE('2021-08-08')) as month_from_start_of_the_year;
                  
select day(current_date) as Day_from_start_of_the_year;          --NO OF DAYS FROM START OF THE MONTH     
select day(DATE('2009-09-24')) as Day; 

--GET LAST DAY OF CURRENT MONTH                  
select LAST_DAY(CURRENT_DATE) AS LAST_DAY_OF_CURRENT_MONTH;

--GET LAST DAY OF ANY MONTH
select LAST_DAY(DATE('1998-09-24')) AS LAST_DAY_OF_CURRENT_MONTH;

--GET LAST DAY OF PREVIOS MONTH                  
select LAST_DAY(CURRENT_DATE-INTERVAL'1 MONTH') AS LAST_DAY_OF_CURRENT_MONTH;                  
                  
--GET LAST DAY OF PREVIOUS MONTH
select LAST_DAY(DATE('1998-09-24')-INTERVAL'1 MONTH') AS LAST_DAY_OF_CURRENT_MONTH;
                  
--GET LAST DAY OF ANY MONTH
select LAST_DAY(DATE('1998-09-24')-INTERVAL'3 MONTH') AS LAST_DAY_OF_CURRENT_MONTH;   

--GET ANY NO OF DAYS BACK DATE                  
SELECT DAY(DATE('2019-08-08')-INTERVAL'20 DAY') AS DAYS_20_BACK_FROM_GIVEN_DATE;
                  
--GET BACK IN DAYS                  
SELECT DATE(DATE('2019-08-08')-INTERVAL'5 DAY') AS  FIVE_DAYS_BACK_FROM_GIVEN_DATE;
SELECT DAY(DATE('2019-08-08')-INTERVAL'15 DAY') AS  FIFTEEN_DAYS_BACK_FROM_GIVEN_DATE; --DON'T SPECIFY MONTH IN DECIMAL EITHER WRITE IT IN DAYS

SELECT DATE(DATE('2019-08-08')-INTERVAL'2 WEEKS') AS  TWO_WEEKS_BACK_FROM_GIVEN_DATE;
SELECT DATE(DATE('2019-08-08')-INTERVAL'2 MONTHS') AS TWO_MONTHS_BACK_FROM_GIVEN_DATE;
                  
--QUARTER(WE HAVE 4 QUAERTER OF 3 MONTHS IN A YEAR)
SELECT QUARTER(CURRENT_DATE) AS QTR;  
SELECT QUARTER(DATE('2022-09-24')) AS QTR_OF_GIVEN_DATE;

--EXTRACT                 
SELECT EXTRACT(YEAR FROM CURRENT_DATE) AS YEAR; 
SELECT EXTRACT(YEAR FROM DATE('2022-05-18')) AS YEAR; 

--USE EXTRACT FOR MONTH WHEN THERE IS DATA ONLY OF 1 YEAR IF MORE THAN ONE YEAR THEN USE DATE_TRUNC AS IT WILL GIVE YEAR WITH MONTH SO IT WILL BE EASY FOR US TO KNOW WHICH YEAR MONTH WE ARE TALKING ABOUT
                  
SELECT EXTRACT(MONTH FROM CURRENT_DATE) AS MONTH;
SELECT EXTRACT(MONTH FROM DATE('2003-06-28')) AS MONTH; 
                  
--TO_DATE OR DATE FUNCTION(IT WILL CHANGE ANY FORMAT OF DATE INTO YYYY-MM-DD FORMAT AS SNOWFLAKE HAS BY DEFAULT THIS FORMAT)
SELECT DATE('24-09-2022','DD-MM-YYYY') AS DATE;--IF WE ARE WRITTING DATE IN ANY FORMAT THEN ALSO WRITE ITS FORMAT AFTER COMMA
SELECT DATE('08-09-2022','MM-DD-YYYY') AS DATE;
SELECT TO_DATE('2022-10-31') AS DATE;
                  SELECT TO_DATE('05-08-2023','MM-DD-YYYY') AS DATE;
                  
 --TO_CHAR FUNCTION(WE ARE CONVERTING INTO CHARACTER SO IT HELPS TO WRITE IN ANY FORMAT)
SELECT TO_CHAR(DATE('1993-08-17'),'DD-MM-YY') AS DD_MM_YY;--1ST CLIENT REQUIREMENT
SELECT TO_CHAR(TO_DATE('2003-10-27'),'MM-YYYY') AS MM_YY;--2ND CLIENT REQUIREMENT
SELECT TO_CHAR(TO_DATE('2003-10-27'),'MON-YYYY') AS MONTH_YYYY;--3RD CLIENT REQUIREMENT
SELECT TO_CHAR(TO_DATE('2003-10-27'),'MON-YY') AS MONTH_YY;--4TH CLIENT REQUIREMENT                  
SELECT TO_CHAR(TO_DATE('2003-10-27'),'DY') AS DAY;--5TH CLIENT REQUIREMENT,IF WE USE DAY INSTEAD OF DY THEN IT WILL NOT WORK IN CODE
SELECT TO_CHAR(TO_DATE('2003-10-27'),'DY-DD-MM-YYYY') AS DAY_DATE;--6TH CLIENT REQUIREMENT
SELECT TO_CHAR(TO_DATE('2003-10-27'),'DD-MM-YYYY-DY') AS DATE_DAY;--7TH CLIENT REQUIREMENT, 
SELECT TO_CHAR(TO_DATE('2003-10-27'),'YYYY-DD') AS YYYY_DD;--8TH CLIENT REQUIREMENT,DD GIVES DATE IN NUMBER WHERE AS DY GIVES DAY NAME
SELECT TO_CHAR(TO_DATE('2003-10-27'),'DD-MM') AS DD_MM;--9TH CLIENT REQUIREMENT  
SELECT TO_CHAR(TO_DATE('20-09-2023'),'DD-MM') AS DD_MM;-- we can't write date in this format
--DAYNAME(USED WHEN CLIENT ASK DAY)
SELECT DAYNAME('2004-08-08');--OR         
SELECT DAYNAME(TO_DATE('2004-08-08'));
SELECT DAYNAME(CURRENT_DATE);
                  
--DATEDIFF(DATE DIFFERENCE)
SELECT DATEDIFF('MONTH','2021-06-08','2022-08-09');
SELECT DATEDIFF('MONTH','2019-06-08','2014-08-09');
SELECT DATEDIFF('YEAR','2011-06-08','2022-08-09');
SELECT DATEDIFF('DAY','2021-06-08','2022-08-09');
SELECT DATEDIFF('WEEK','2021-06-08','2022-08-09');    
              
                  
select datediff('month','2023-09-08','2024-08-07') as original_date;
SELECT                   
                  
SELECT DISTINCT * FROM SK_CONSUMER_COMPLAINTS WHERE DATE_RECEIVED BETWEEN '29-07-2013' AND '31-07-2013';--BETWEEN ALSO INCLUDE THE INITIAL AS WELL AS FINAL
--MEANS RESULT WILL INCLUDE 29,30 AND 31-07-2013
--BETWEEN USED IN CONTINUOUS DATA WHEREVER RANGE IS GIVEN
SELECT DISTINCT * FROM SK_CONSUMER_COMPLAINTS WHERE DATE_RECEIVED BETWEEN '29-07-2013' AND '31-07-2013';